### ISSUE TITLE
Does the ludibrio supports python-2.5?

### ISSUE THREAD

**Issue by generalov** [nsigustavo/ludibrio#5]
Ubuntu 8.04, python-2.5.2, and ludibrio-3.0.3, installed into the
virtualenv-1.5.1 `/tmp/python/`. I try to launch code from the `Mock()` example:

```
#!/usr/bin/env python
from __future__ import with_statement

from ludibrio import Mock
with Mock() as MySQLdb:
    con = MySQLdb.connect('server', 'user', 'XXXX') # mock

con = MySQLdb.connect('server', 'user', 'XXXX')
```

I expect this code should be correct (and it works on Ubuntu 10.04 with
python2.6), but here I got a traceback:

```
$ /tmp/python/bin/python test.py 
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    con = MySQLdb.connect('server', 'user', 'XXXX') # mock
  File "/tmp/python/lib/python2.5/site-packages/ludibrio/mock.py", line 99, in __getattr__
    return self._property_called('__getattribute__',[x])
  File "/tmp/python/lib/python2.5/site-packages/ludibrio/mock.py", line 38, in _property_called
    self.__traceroute_expected__.remember()
  File "/tmp/python/lib/python2.5/site-packages/ludibrio/traceroute.py", line 13, in remember
    traceinfo = getframeinfo(frame)
  File "/usr/lib/python2.5/inspect.py", line 840, in getframeinfo
    lines, lnum = findsource(frame)
  File "/usr/lib/python2.5/inspect.py", line 508, in findsource
    pat = re.compile(r'^(\s*def\s)|(.*(?<!\w)lambda(:|\s))|^(\s*@)')
  File "/tmp/python/lib/python2.5/re.py", line 188, in compile
    return _compile(pattern, flags)
  File "/tmp/python/lib/python2.5/re.py", line 239, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/tmp/python/lib/python2.5/sre_compile.py", line 505, in compile
    import sre_parse
  File "/tmp/python/lib/python2.5/site-packages/ludibrio/dependencyinjection.py", line 31, in import_double
    if not fromlist:raise ImportError('Use: from ... import ...')
ImportError: Use: from ... import ...
```

Should I expect the `ludibrio` supports the `python-2.5`?

**Comment by nsigustavo** [comment]
upgrade to new versions... in github
